### ISSUE TITLE
Welcome page can not be reopened

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-quarkus#115]
- Open the welcome page (using command or opening application.properties)
- close it
- reopen it (using command)
=> fails to open:

```
stack trace: Error: Webview is disposed
	at u.assertNotDisposed (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:623:612)
	at u.get webview [as webview] (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:622:315)
	at WelcomeWebview.<anonymous> (/Users/fbricon/Dev/projects/vscode-quarkus/dist/extension.js:82437:25)
	at Generator.next (<anonymous>)
	at /Users/fbricon/Dev/projects/vscode-quarkus/dist/extension.js:82382:71
	at new Promise (<anonymous>)
	at /Users/fbricon/Dev/projects/vscode-quarkus/dist/extension.js:82378:12
	at WelcomeWebview.setPanelHtml (/Users/fbricon/Dev/projects/vscode-quarkus/dist/extension.js:82436:16)
	at /Users/fbricon/Dev/projects/vscode-quarkus/dist/extension.js:82483:22
	at l.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:50:652)
	at x.$acceptConfigurationChanged (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:659:623)
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:659:36
```

**Comment by fbricon** [comment]
See https://code.visualstudio.com/api/extension-guides/webview for pointers
