### ISSUE TITLE
Completion in non-quarkus/non-mp project causes errors

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-quarkus#247]
- open a non quarkus/non-mp project (eg. lemminx)
- start the vscode-quarkus extension by opening the quarkus project wizard, close it
- open one of the java files
- trigger autocompletion
=> this is logged in the Quarkus Tools console:
```
[Error - 11:51:47 p.m.] Request textDocument/completion failed.
Error: The received response has neither a result nor an error property.
	at /Users/fbricon/.vscode/extensions/redhat.vscode-quarkus-1.4.0/dist/extension.js:1:41034
	at /Users/fbricon/.vscode/extensions/redhat.vscode-quarkus-1.4.0/dist/extension.js:1:41115
	at Immediate.<anonymous> (/Users/fbricon/.vscode/extensions/redhat.vscode-quarkus-1.4.0/dist/extension.js:1:41132)
	at processImmediate (internal/timers.js:439:21)
```

**Comment by angelozerr** [comment]
@fbricon please try my PR https://github.com/redhat-developer/quarkus-ls/pull/308 which should fix this issue.
